# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\phone\get_ phones_single_id.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetPhonesSingleId(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-type-value": [
                    ["查询一个不存在的用户ID", 1, ""],
                    ["查询一个没有绑定手机号的用户ID", 2, ""],
                    ["查询一个绑定了手机号的用户ID", 3, "hashedPhoneNumber"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/phones/single/id 通过用户ID获取手机号")
        .variables(**{"url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .setup_hook("${phone_single_id($request,$url,$type)}")
            .get("/phones/single/")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "$value")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetPhonesSingleId().test_start()
