# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\phone\post_ phones_batch.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePostPhonesBatch(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-type-value": [
                    ["查询一个用户ID的手机信息", 1, "encryptedPhoneNumber"],
                    ["查询多个用户ID的手机信息", 2, "hashedPhoneNumber"],
                    ["查询用户ID没有绑定手机", 3, ""],
                    ["查询用户ID不存在", 4, ""],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/phones/batch 批量获取手机号信息")
        .variables(**{"url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .setup_hook("${phone_batch($request,$url,$type)}")
            .post("/phones/batch")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "$value")
        ),
    ]


if __name__ == "__main__":
    TestCasePostPhonesBatch().test_start()
