# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_api\login\post_accounts_captcha_login_silence.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePostAccountsCaptchaLoginSilence(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-phone_number-pid-status_code-msg": [
                    ["发送登入验证码-静默登录-输入已经注册的手机号发送验证码", "14266669997", "account", 204, ""],
                    ["发送登入验证码-静默登录-输入未注册的手机号发送验证码", "14266662355", "account", 204, ""],
                    [
                        "发送登入验证码-静默登录-手机验证码发送频繁",
                        "14266662355",
                        "account",
                        403,
                        "发送验证码过于频繁",
                    ],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/tiger/v3/app/accounts/captcha/login/silence发送登入验证码-静默登录")
        .variables(
            **{
                "base_url": "${ENV(ACCOUNT_API_URL)}",
                "ticket": "${accounts_api_ticket($base_url)}",
            }
        )
        .base_url("${ENV(ACCOUNT_API_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .post("/tiger/v3/app/accounts/captcha/login/silence")
            .with_headers(**{"X-Captcha-Ticket": "$ticket"})
            .with_json({"phone_number": "$phone_number", "pid": "$pid"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsCaptchaLoginSilence().test_start()
