# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_api\login\post_accounts_special_login.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePostAccountsSpecialLogin(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-Origin-Client-Version-status_code-msg": [
                    [
                        "登录-来源网址在禁用名单内",
                        "https://creation.codemao.cn",
                        "",
                        "",
                        403,
                        "域名已被禁止访问此接口",
                    ],
                    ["登录-来源网址不在禁用名单内", "https://api.codemao.cn", "", "", 200, "token"],
                    ["登录-传Client-Id", "", "web", "", 200, "token"],
                    ["登录-传Auth-Version", "", "", "1.0.0", 200, "refresh"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/tiger/v3/app/accounts/login 用户名密码登录-特殊登录场景").base_url(
        "${ENV(ACCOUNT_API_URL)}"
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .post("/tiger/v3/web/accounts/login")
            .with_headers(
                **{
                    "Origin": "$Origin",
                    "Client-Id": "$Client",
                    "Auth-Version": "$Version",
                }
            )
            .with_json({"identity": 14266669999, "password": 123456, "pid": "account"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsSpecialLogin().test_start()
