# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_api\login\post_accounts_logout.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCasePostAccountsLogout(HttpRunner):

    config = Config("/tiger/v3/app/accounts/logout 退出登录").base_url(
        "${ENV(ACCOUNT_API_URL)}"
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/tiger/v3/web/accounts/login")
            .with_json({"identity": 14266669999, "password": 123456, "pid": "account"})
            .extract()
            .with_jmespath("body.auth.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "token")
        ),
        Step(
            RunRequest("获取用户信息")
            .get("/tiger/v3/app/accounts/profile")
            .with_headers(**{"Authorization": "$token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "id")
        ),
        Step(
            RunRequest("退出登录")
            .post("/tiger/v3/web/accounts/logout")
            .with_headers(**{"Authorization": "$token"})
            .validate()
            .assert_equal("status_code", 204)
        ),
        Step(
            RunRequest("获取用户信息")
            .get("/tiger/v3/app/accounts/profile")
            .with_headers(**{"Authorization": "$token"})
            .validate()
            .assert_equal("status_code", 403)
            .assert_contains(
                "text", "Full authentication is required to access this resource"
            )
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsLogout().test_start()
