# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\delete_accounts_id_phone_number.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseDeleteAccountsIdPhoneNumber(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-type-status_code-msg": [
                    ["正常解绑手机号", 1, 204, ""],
                    ["解绑手机号-用户未设置用户名", 2, 403, "ShouldSetUsernameException"],
                    ["解绑手机号-用户设置了用户名，没有设置密码", 3, 403, "ShouldSetPasswordException"],
                    ["解绑手机号-用户设置了邮箱，没有设置密码", 4, 403, "ShouldSetPasswordException"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/accounts/{id}/phone_number解绑手机")
        .variables(**{"url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .with_variables(**{"user_id": "${delete_phone($type,$url)}"})
            .delete("/accounts/$user_id/phone_number")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeleteAccountsIdPhoneNumber().test_start()
