# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\delete_accounts_id_email.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseDeleteAccountsIdEmail(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-type-status_code-msg": [
                    ["解绑邮箱-用户只绑定了手机号", 1, 204, ""],
                    ["解绑邮箱-用户设置了用户名密码", 2, 204, ""],
                    [
                        "解绑邮箱-用户设置了用户名没有设置密码",
                        3,
                        422,
                        "ShouldBindPhoneOrSetUsernameOrEmailWithPassword",
                    ],
                    [
                        "解绑邮箱-用户没有绑定手机号和用户名密码",
                        4,
                        422,
                        "ShouldBindPhoneOrSetUsernameOrEmailWithPassword",
                    ],
                    ["解绑邮箱-用户没有绑定邮箱", 5, 204, ""],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/accounts/{id}/unbindEmail解绑邮箱")
        .variables(**{"url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .with_variables(**{"user_id": "${delete_email($type,$url)}"})
            .delete("/accounts/$user_id/unbindEmail")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeleteAccountsIdEmail().test_start()
