# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\get_accounts_id_basic_auth.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetAccountsIdBasicAuth(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-user_id-status_code-type": [
                    ["查询存在的用户ID", 10000, 200, 1],
                    ["查询一个不存在的用户ID", 100, 422, 2],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/accounts/{id}/basic_auth 获取主账号信息").base_url("${ENV(BASE_URL)}")

    teststeps = [
        Step(
            RunRequest("$name")
            .with_variables(**{"foo1": "${return_random_string_3($type)}"})
            .get("/accounts/$user_id/basic_auth")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$foo1")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAccountsIdBasicAuth().test_start()
