# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\get_accounts_identity_check.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetAccountsIdentityCheck(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-identity-status_code-msg": [
                    ["使用一个已经注册的手机号查询", 13037375544, 200, "phone_number"],
                    ["使用一个未注册的手机号查询", "144091723854", 204, ""],
                    ["使用一个已经注册的用户名查询", "qinwang1997", 200, "username"],
                    ["使用一个未注册的用户名查询", "nysp1542", 204, ""],
                    ["使用一个已经注册的邮箱查询", "1583492267@qq.com", 200, "email"],
                    ["使用一个未注册的用户名查询", "kjdsdsds@okju.com", 204, ""],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("检查主账号注册情况(手机号、用户名、邮箱)").base_url("${ENV(BASE_URL)}")

    teststeps = [
        Step(
            RunRequest("$name")
            .get("/accounts/identity/check")
            .with_params(**{"identity": "$identity"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAccountsIdentityCheck().test_start()
