# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\get_accounts_id.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetAccountsId(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-user_id-fields-status_code-type": [
                    ["查询存在的用户ID", 10000, "", 200, 1],
                    ["查询一个不存在的用户ID", 100, "", 204, 3],
                    ["查询一个错误的用户ID", "abc", "", 404, 3],
                    ["带fields参数查询", 10000, "id,username,email,phone_number", 200, 2],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/accounts/{id}获取用户信息").base_url("${ENV(BASE_URL)}")

    teststeps = [
        Step(
            RunRequest("$name")
            .with_variables(
                **{
                    "foo1": "${return_random_string($type)}",
                    "foo2": "${return_random_string($type)}",
                }
            )
            .get("/accounts/$user_id")
            .with_params(**{"fields": "$fields"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$foo1")
            .assert_contains("text", "$foo2")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAccountsId().test_start()
