# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\get_accounts_id_oauth.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetAccountsIdOauth(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-user_id-status_code-oauth_type": [
                    ["查询用户的微信授权信息", "$foo1", 200, "WECHAT"],
                    ["查询用户的QQ授权信息", "$foo1", 200, "QQ"],
                    ["查询没有绑定微信的用户的微信授权信息", "$foo2", 200, "WECHAT"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/accounts/{id}/oauth通过用户id获取第三方授权信息")
        .variables(
            **{"foo1": "${ENV(ENV_USER_ID)}", "foo2": "${ENV(NO_OAUTH_USER_ID)}"}
        )
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .get("/accounts/$user_id/oauth")
            .with_params(**{"oauth_type": "$oauth_type"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "id")
            .assert_contains("text", "unionid")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAccountsIdOauth().test_start()
