# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\get_accounts.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetAccounts(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-user_ids-fields-status_code-type": [
                    ["查询单个用户ID", 10000, "", 200, 1],
                    ["查询多个用户ID", "10000,10001", "", 200, 1],
                    [
                        "带fields查询用户",
                        "10000,10001",
                        "id,username,email,phone_number",
                        200,
                        2,
                    ],
                    ["查询一个不存在的用户ID", "1000", "", 200, 3],
                    ["用户ID为空进行查询", "", "", 400, 4],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/accounts 批量用户id搜索用户信息").base_url("${ENV(BASE_URL)}")

    teststeps = [
        Step(
            RunRequest("$name")
            .with_variables(
                **{
                    "foo1": "${return_random_string($type)}",
                    "foo2": "${return_random_string($type)}",
                }
            )
            .get("/accounts")
            .with_params(**{"user_ids": "$user_ids", "fields": "$fields"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$foo1")
            .assert_contains("text", "$foo2")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAccounts().test_start()
