# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\get_accounts_business.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetAccountsBusiness(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-url_data-foo1": [
                    ["查询一个用户ID", "user_ids=10000", "age_section_id"],
                    ["查询多个用户ID", "user_ids=10000&user_ids=10001", "doing"],
                    ["查询一个不存在的用户ID", "user_ids=100", ""],
                    [
                        "带fields参数查询",
                        "user_ids=10000&fields=id&fields=age_section_id&fields=mlz_name&fields=gold",
                        "mlz_name",
                    ],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/accounts/business 批量用户id搜索用户拓展信息").base_url("${ENV(BASE_URL)}")

    teststeps = [
        Step(
            RunRequest("$name")
            .get("/accounts/business?$url_data")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "$foo1")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAccountsBusiness().test_start()
