# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\get_accounts_phone_check.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetAccountsPhoneCheck(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-phone_number-msg": [
                    ["使用一个不符合规则的手机号查询", "120245c", "false"],
                    ["使用一个已注册的手机号查询", "13037375544", "true"],
                    ["使用一个未注册的手机号查询", "142033849564", "false"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/accounts/phone/check 检查手机号在编程猫平台账号的注册情况").base_url(
        "${ENV(BASE_URL)}"
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .get("/accounts/phone/check")
            .with_params(**{"phone_number": "$phone_number"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAccountsPhoneCheck().test_start()
