# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\get_accounts_id_business.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetAccountsIdBusiness(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-user_id-fields-status_code-type": [
                    ["查询存在的用户ID", 10000, "", 200, 1],
                    ["查询一个不存在的用户ID", 100, "", 204, 2],
                    ["查询一个错误的用户ID", "abc", "", 404, 2],
                    ["带fields参数查询", 10000, "id", 200, 3],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/accounts/{id}/business 获取用户拓展信息").base_url("${ENV(BASE_URL)}")

    teststeps = [
        Step(
            RunRequest("$name")
            .with_variables(**{"foo1": "${return_random_string_4($type)}"})
            .get("/accounts/$user_id/business")
            .with_params(**{"fields": "$fields"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$foo1")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAccountsIdBusiness().test_start()
