# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\patch_accounts_id_username.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePatchAccountsIdUsername(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-user_ids-username-status_code-msg-code": [
                    [
                        "用户已经设置了用户名",
                        "$user_id",
                        "qinwan1g2",
                        403,
                        "UserCanNotRepeatSettingUsernameException",
                        1,
                    ],
                    ["用户设置username", 1, "", 204, "", 2],
                    [
                        "设置的用户名已存在",
                        "$user_id",
                        "qinwang123",
                        403,
                        "ExistSameUsernameException",
                        1,
                    ],
                    [
                        "设置的用户名不符合规则",
                        "$user_id",
                        "2qinwang",
                        400,
                        "MethodArgumentNotValidException",
                        1,
                    ],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/accounts/{id}/username设置用户名")
        .variables(**{"user_id": "${ENV(PUT_USER_ID)}", "url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .setup_hook("${update_patch_accounts_username($request,$code,$url)}")
            .patch("/accounts/$user_id/username")
            .with_json({"username": "$username"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCasePatchAccountsIdUsername().test_start()
