# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\post_accounts_password_setting.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePostAccountsPasswordSetting(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-code-status_code-msg": [
                    ["首次设置密码-传不存在的user_id", 1, 422, "用户需要有主账号"],
                    ["首次设置密码-密码长度小于6位", 2, 400, "size must be between 6 and 20"],
                    ["首次设置密码-密码长度大于20位", 3, 400, "size must be between 6 and 20"],
                    ["首次设置密码-用户已经设置过密码", 4, 422, "初始密码只能设置一次"],
                    ["首次设置密码-新用户首次设置密码", 5, 204, ""],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/accounts/password/setting 首次设置密码")
        .variables(**{"url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .setup_hook("${accounts_password_setting($request,$url,$code)}")
            .post("/accounts/password/setting")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsPasswordSetting().test_start()
