# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\post_accounts_list.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePostAccountsList(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-status_code-msg-type": [
                    ["搜索用户信息-搜索已经注册的用户ID ", 200, "id", 1],
                    ["搜索用户信息-搜索不存在的用户ID ", 200, "items", 2],
                    ["搜索用户信息-搜索fullname ", 200, "fullname", 3],
                    ["搜索用户信息-搜索一个已经注册的手机号 ", 200, "phone_number", 4],
                    ["搜索用户信息-搜索没有注册的手机号 ", 200, "total", 5],
                    ["搜索用户信息-通过昵称搜索用户 ", 200, "nickname", 6],
                    ["搜索用户信息-使用单个字段查询用户 ", 200, "id", 7],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/accounts/list/search 搜索用户信息")
        .variables(**{"url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .setup_hook("${accounts_list_search($request,$type)}")
            .post("/accounts/list/search")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsList().test_start()
