# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\post_accounts_usernames_check.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePostAccountsUsernamesCheck(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-username-status_code-msg": [
                    ["批量检测用户名是否存在-传一个已经存在的用户名", ["qinwang1997"], 200, "true"],
                    ["批量检测用户名是否存在-传一个不存在的用户名", ["qwang19397"], 200, "false"],
                    ["批量检测用户名是否存在-传多个用户名", ["qinwang1997", "qinwang123"], 200, "true"],
                    ["批量检测用户名是否存在-传非正确格式的用户名", ["秦旺"], 200, "false"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/accounts/usernames/check 批量检测用户名是否存在").base_url(
        "${ENV(BASE_URL)}"
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .post("/accounts/usernames/check")
            .with_json({"usernames": "$username"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsUsernamesCheck().test_start()
