# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\post_accounts_auth.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePostAccountsAuth(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-code-status_code-msg": [
                    ["登录校验-输入正确手机号密码", 1, 200, "id"],
                    ["登录校验-输入正确邮箱密码", 2, 200, "id"],
                    ["登录校验-输入正确用户名密码", 3, 200, "id"],
                    ["登录校验-用户不存在", 4, 422, "用户不存在"],
                    ["登录校验-密码错误", 5, 422, "密码错误"],
                    ["登录校验-identity传空", 6, 400, "size must be between 1 and 50"],
                    [
                        "登录校验-password传空",
                        7,
                        400,
                        "size must be between 1 and 2147483647",
                    ],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/accounts 登录校验")
        .variables(**{"url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .setup_hook("${account_auth_check($request,$code,$url)}")
            .post("/accounts/auth")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsAuth().test_start()
