# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\post_accounts_register.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePostAccountsRegister(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "name-code-status_code-msg": [
                    ["通用批量用户名注册-传不存在的pid", 1, 403, "不合法的pid"],
                    ["通用批量用户名注册-pid传空", 2, 400, "size must be between 1 and 10"],
                    ["通用批量用户名注册-fullname不符合规则", 3, 400, "u2E80"],
                    ["通用批量用户名注册-identityType不传 1和2", 4, 400, "identityType"],
                    ["通用批量用户名注册-手机号注册", 5, 200, "has_password"],
                    ["通用批量用户名注册-邮箱注册", 6, 200, "is_create"],
                    ["通用批量用户名注册-手机号已经注册", 7, 200, "has_password"],
                    ["通用批量用户名注册-邮箱已经注册", 8, 200, "is_create"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("/accounts/register B端:注册接口").base_url("${ENV(BASE_URL)}")

    teststeps = [
        Step(
            RunRequest("$name")
            .setup_hook("${accounts_register($request,$code)}")
            .post("/accounts/register")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("text", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsRegister().test_start()
