# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\put_accounts_id.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePutAccountsId(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"num-name-fields-status_code-value": "${put_accounts()}"})
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/accounts 更新用户信息")
        .variables(**{"user_id": "${ENV(PUT_USER_ID)}", "url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("$name")
            .setup_hook("${update_accounts_put($request,$fields)}")
            .put("/accounts/$user_id")
            .teardown_hook("${time_sleep()}")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal("${select_mysql_date($num,$user_id)}", "$value")
        ),
    ]


if __name__ == "__main__":
    TestCasePutAccountsId().test_start()
