# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\staff.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseStaff(HttpRunner):

    config = (
        Config("外部用户跟内部账号绑定 - 通过用户id获取用户内部职工资料- 批量获取用户内部职工资料-移除用户-内部账号关系 ")
        .variables(**{"url": "${ENV(BASE_URL)}"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("添加用户-内部账号关系")
            .post("/accounts/staff")
            .with_json([{"employeeState": 1, "internalId": 2, "userId": 10000}])
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("用户-内部账号关系单个 查询")
            .get("/accounts/staff/10000")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "employeeState")
        ),
        Step(
            RunRequest("用户-内部账号关系批量 查询")
            .get("/accounts/staff?userIds=10000")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "internalId")
        ),
        Step(
            RunRequest("移除用户-内部账号关系")
            .post("/accounts/staff/remove")
            .with_json({"ids": [10000]})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("用户-内部账号关系单个 查询")
            .get("/accounts/staff/10000")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "")
        ),
    ]


if __name__ == "__main__":
    TestCaseStaff().test_start()
