# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_hub\account\weak_password.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseWeakPassword(HttpRunner):

    config = (
        Config("弱密码相关")
        .variables(**{"password": "qinqin8"})
        .base_url("${ENV(BASE_URL)}")
    )

    teststeps = [
        Step(
            RunRequest("添加弱密码")
            .post("/accounts/weak-password")
            .with_json({"passwords": ["$password"]})
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "")
        ),
        Step(
            RunRequest("获取全部弱密码")
            .get("/accounts/weak-password/all")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "$password")
        ),
        Step(
            RunRequest("检测是否弱密码")
            .get("/accounts/weak-password/check")
            .with_params(**{"password": "$password"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "true")
        ),
        Step(
            RunRequest("移除弱密码")
            .delete("/accounts/weak-password/delete")
            .with_params(**{"password": "$password"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("检测是否弱密码")
            .get("/accounts/weak-password/check")
            .with_params(**{"password": "$password"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "false")
        ),
    ]


if __name__ == "__main__":
    TestCaseWeakPassword().test_start()
