# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_api\token\post_accounts_cookie_info.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCasePostAccountsCookieInfo(HttpRunner):

    config = Config("/tiger/v3/web/accounts/cookie/info getCookie").base_url(
        "${ENV(ACCOUNT_API_URL)}"
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/tiger/v3/web/accounts/login")
            .with_json({"identity": 14266669999, "password": 123456, "pid": "account"})
            .extract()
            .with_jmespath("body.auth.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "token")
        ),
        Step(
            RunRequest("getCookie")
            .post("/tiger/v3/web/accounts/cookie/info")
            .with_json({"token": "$token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "cookie_value")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsCookieInfo().test_start()
