# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcases\account_api\token\post_accounts_user_token_expires.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCasePostAccountsUserTokenExpires(HttpRunner):

    config = Config("/tiger/user_token/expires getUserTokenExpires").base_url(
        "${ENV(ACCOUNT_API_URL)}"
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/tiger/v3/web/accounts/login")
            .with_json({"identity": 14266669999, "password": 123456, "pid": "account"})
            .extract()
            .with_jmespath("body.auth.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "token")
        ),
        Step(
            RunRequest("getUserTokenExpires")
            .get("/tiger/user_token/expires")
            .with_headers(**{"Authorization": "$token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("text", "expired_at")
        ),
    ]


if __name__ == "__main__":
    TestCasePostAccountsUserTokenExpires().test_start()
